[package]
name = "fuckyouspammer"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.10.0", features = ["gateway", "extras", "model", "collector", "unstable_discord_api", "reqwest"] }
tokio = { version = "1.36.0", features = ["full"] }
